### ISSUE TITLE
Link to Project

### ISSUE THREAD

**Issue by noobjey** [mitchashby16/traffic_spy#18]

**Comment by noobjey** [comment]
https://github.com/JumpstartLab/curriculum/blob/5cd41b3635cc4d32431032d42bcfc9f7da3135d5/source/projects/traffic_spy.markdown

**Comment by dsshim** [comment]
We noticed you recently created a branch in GitHub. Did you know that we’ll move an issue to ‘in progress’ and assign it to you if you reference it in the branch name? Just put the issue number at the beginning of the branch name with a '-' or '_' behind it or anywhere else in the branch name with a '#' in front of it.

Here are some example branch names:

123-fix-bug

bug-fix#123

bug-fix-username/repo#123  (issue in another repo)

This prevents us from moving issues based off other numbers sometimes used in branch names.

Let us know if you like it!
